vars: {
  d2-config: {
    layout-engine: elk
  }
}

style: {
  fill: transparent
}

direction: right

internet: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
}

internet -> cloud.cloudInstance: flipt.cloud {
  style.font-size: 32
}
internet -> cloud.environments.fone: environment-org.flipt.cloud {
  style.font-size: 32
}

cloud: "" {
  style: {
    fill: transparent
  }

  cloudInstance: Flipt Cloud {
    shape: image
    icon: https://flipt.cloud/icon.svg?3c7bba14eb804cba
    style.font-size: 32
  }

  environments: Environments {
    style: {
        fill: transparent
        stroke: "#000000"
        stroke-dash: 3
    }

    fone: "" {
        icon: https://assets-global.website-files.com/659480aa07716c37f0fd8dee/6597f2baa456ff33c9f13a07_logo%201.svg
    }

    ftwo: "" {
        icon: https://assets-global.website-files.com/659480aa07716c37f0fd8dee/6597f2baa456ff33c9f13a07_logo%201.svg
    }

    fthree: "" {
        icon: https://assets-global.website-files.com/659480aa07716c37f0fd8dee/6597f2baa456ff33c9f13a07_logo%201.svg
    }
  }
}

github: "GitHub" {
  shape: image
  icon: https://icons.terrastruct.com/dev%2Fgithub.svg
  style.font-size: 32
}

cloud.environments.fone <-> github
cloud.environments.ftwo <-> github
cloud.environments.fthree <-> github