name = "flipt-docs-redirect"
main = "src/index.ts"
compatibility_date = "2024-09-27"

# Development configuration
[env.development]
[env.development.vars]
ORIGIN_URL = "http://localhost:3000"

# Production configuration  
# Uncomment and update when deploying to production
# [env.production]
# route = "docs.flipt.io/*"
# zone_id = "YOUR_ZONE_ID"
# [env.production.vars]
# ORIGIN_URL = "https://docs-origin.flipt.io"

# Observability
[observability]
enabled = true

# If you need to bind to other services or KV namespaces
# [kv_namespaces]
# binding = "KV"
# id = "YOUR_KV_NAMESPACE_ID"

