name: Test Worker Redirects

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      # Deploy preview
      - name: Deploy Worker Preview
        id: deploy
        run: |
          PREVIEW_URL=$(wrangler deploy --env preview --dry-run=remote --out json | jq -r '.previews[0].url')
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT

      - name: Run redirect tests
        id: tests
        run: |
          set -euo pipefail

          BASE_URL="${{ steps.deploy.outputs.preview_url }}"
          echo "Testing against preview URL: $BASE_URL"

          echo "Testing root → /v2/"
          LOCATION=$(curl -s -o /dev/null -w "%{redirect_url}" $BASE_URL/)
          test "$LOCATION" = "$BASE_URL/v2/"

          echo "Testing unversioned path → /v1/path"
          LOCATION=$(curl -s -o /dev/null -w "%{redirect_url}" $BASE_URL/getting-started)
          test "$LOCATION" = "$BASE_URL/v1/getting-started"

          echo "Testing already versioned path (/v1) → no redirect"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $BASE_URL/v1/getting-started)
          test "$STATUS" -eq 200

          echo "Testing already versioned path (/v2) → no redirect"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $BASE_URL/v2/getting-started)
          test "$STATUS" -eq 200

          echo "Testing excluded path (.css) → no redirect"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $BASE_URL/styles.css)
          test "$STATUS" -eq 200

          echo "✅ All redirect tests passed!"
